[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram==2.25.1",
    "aiohttp==3.8.6",
    "apscheduler==3.10.4",
    "reportlab==4.2.2",
]
