services:
  - type: web
    name: mindmeld-telegram-bot
    env: python
    region: frankfurt
    plan: free
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        # значение забираем из Render → Environment, поэтому в yaml без value
        sync: false
